
services:
  mysql:
    image: mysql:8
    container_name: skribbl_mysql
    environment:
      MYSQL_DATABASE: skribbl
      MYSQL_USER: skribbl
      MYSQL_PASSWORD: skribbl123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3309:3306" 
    volumes:
      - skribbl_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    container_name: skribbl_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/skribbl?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: skribbl
      SPRING_DATASOURCE_PASSWORD: skribbl123
    depends_on:
      mysql:
        condition: service_healthy
  

  frontend:
    build: ./frontend
    container_name: skribbl_frontend
    depends_on:
      - backend
    ports:
      - "8088:80" 

volumes:
  skribbl_mysql_data:
